// Generated by gencpp from file robot_pkg/robot_msg.msg
// DO NOT EDIT!


#ifndef ROBOT_PKG_MESSAGE_ROBOT_MSG_H
#define ROBOT_PKG_MESSAGE_ROBOT_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_pkg
{
template <class ContainerAllocator>
struct robot_msg_
{
  typedef robot_msg_<ContainerAllocator> Type;

  robot_msg_()
    : text()
    , x(0)  {
    }
  robot_msg_(const ContainerAllocator& _alloc)
    : text(_alloc)
    , x(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;

   typedef int64_t _x_type;
  _x_type x;





  typedef boost::shared_ptr< ::robot_pkg::robot_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_pkg::robot_msg_<ContainerAllocator> const> ConstPtr;

}; // struct robot_msg_

typedef ::robot_pkg::robot_msg_<std::allocator<void> > robot_msg;

typedef boost::shared_ptr< ::robot_pkg::robot_msg > robot_msgPtr;
typedef boost::shared_ptr< ::robot_pkg::robot_msg const> robot_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_pkg::robot_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_pkg::robot_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_pkg::robot_msg_<ContainerAllocator1> & lhs, const ::robot_pkg::robot_msg_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text &&
    lhs.x == rhs.x;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_pkg::robot_msg_<ContainerAllocator1> & lhs, const ::robot_pkg::robot_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_pkg::robot_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_pkg::robot_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_pkg::robot_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_pkg::robot_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_pkg::robot_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_pkg::robot_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_pkg::robot_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "202a3b74963980c3734c0032f172165d";
  }

  static const char* value(const ::robot_pkg::robot_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x202a3b74963980c3ULL;
  static const uint64_t static_value2 = 0x734c0032f172165dULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_pkg::robot_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_pkg/robot_msg";
  }

  static const char* value(const ::robot_pkg::robot_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_pkg::robot_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
"int64 x\n"
;
  }

  static const char* value(const ::robot_pkg::robot_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_pkg::robot_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_pkg::robot_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_pkg::robot_msg_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PKG_MESSAGE_ROBOT_MSG_H
